import './selection.test.mjs';
import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {selectKDNA,createKDNAWebClient,releaseKDNASelection} from '@aikdna/kdna-web-client';
import {bytesFor,inspect,withOptionalSupport} from './fixtures.mjs';
import {startFixture} from './http-fixture.mjs';
let fixture,serial=0;const rich=bytesFor('independent-mechanisms.kdna');
before(async()=>{fixture=await startFixture();});
after(async()=>{const r=await fixture.close();assert.deepEqual(r,{listening:false,open_sockets:0});console.log(JSON.stringify({fixtureClosed:r,pid:process.pid}));});
function config(route='/valid',options={}){return {endpointUrl:fixture.base+route,endpointId:'endpoint:client-components',sessionId:'session:client-components',...options};}
function binding(selection,route='/valid',overrides={},extra={}){const id='request:client:'+ ++serial;const req={request_id:id,tuple:selection.tuple,budget_bytes:1000000,mode:'exact_selection',selection:{asset_id:selection.asset.asset_id,asset_version:selection.asset.asset_version,judgment_id:'judgment-engineering'},handle:null,...overrides};return {association_id:'association:client:'+serial,endpoint_id:'endpoint:client-components',session_id:'session:client-components',endpoint_url:fixture.base+route,issued_at_ms:Date.now(),expires_at_ms:Date.now()+60000,outbound_request_json:JSON.stringify(req),correlation:{state:'validated',request_id:req.request_id},expected_tuple:selection.tuple,expected_asset:selection.asset,expected_digests:Object.fromEntries(['A','C','E'].map(k=>[k,selection.digests[k].observed])),expected_snapshot_id:null,max_response_bytes:1000000,max_read_ms:5000,admission_response_limit_bytes:4096,...extra};}
function received(r,channel='read_envelope'){assert.equal(r.status,'received',JSON.stringify(r));assert.equal(r.view.origin,'remote');assert.equal(r.view.response.channel,channel);assert.deepEqual(r.view.response,r.admission.response);assert.deepEqual(r.view.proof_limits,r.admission.proof_limits);assert.ok(Object.values(r.view.capabilities).every(v=>v===false));assert.equal(r.view.proof_limits.remote_identity,'NOT_PROVEN');assert.equal(r.view.proof_limits.remote_authorization,'NOT_PROVEN');assert.equal(r.view.proof_limits.receipt_delivery,'REMOTE_CLAIM_ONLY');return r.view.response.body;}
function failed(r,code){assert.equal(r.view,null);assert.ok(['failed','rejected'].includes(r.status));if(code)assert.equal(r.code,code,JSON.stringify(r));return r;}
async function exercise(route,run,options={},bytes=rich){const s=await selectKDNA(bytes);assert.equal(s.status,'selected');const c=createKDNAWebClient(config(route,options));try{return await run(c,s.selection);}finally{c.dispose();releaseKDNASelection(s.selection);}}
test('actual Fetch current component envelope matches fresh Core IR, digests and remote proof limits',()=>exercise('/valid',async(c,s)=>{const ctx=binding(s),r=await c.read(s,ctx),body=received(r),core=await inspect(rich);assert.equal(body.status,'ready');assert.deepEqual(body.content.closure.filter(n=>n.role==='method'),core.ir.nodes.filter(n=>n.role==='method'));const kinds=body.content.closure.filter(n=>n.role==='method').flatMap(n=>n.value.component_interpretations.map(x=>x.body.kind));assert.deepEqual([...new Set(kinds)].sort(),['candidate-set','discriminator-set','taxonomy']);assert.deepEqual(body.digests,core.digests);assert.equal(body.request_id,ctx.correlation.request_id);assert.equal(body.receipt.snapshot_id,body.snapshot_id);}));
test('actual Host deny remains a received rejected envelope without disclosure',()=>exercise('/denied',async(c,s)=>{const body=received(await c.read(s,binding(s,'/denied')));assert.equal(body.status,'rejected');assert.equal(body.content,null);assert.ok(body.diagnostics.some(x=>x.code==='READ_HOST_DENIED'));}));
test('replaced blocked asset yields only unproven remote rejection without disclosure',()=>exercise('/blocked',async(c,s)=>{const result=await c.read(s,binding(s,'/blocked'));assert.equal(result.code,null,JSON.stringify(result));const body=received(result);assert.equal(body.status,'rejected');assert.equal(body.content,null);assert.equal(body.states.core,'valid');assert.equal(body.states.interpretation,'blocked');assert.ok(body.diagnostics.some(x=>x.code==='READ_COMPONENT_GRAPH_CYCLE'));}));
test('actual Host admission rejection is retained as its channel',()=>exercise('/valid',async(c,s)=>{const body=received(await c.read(s,binding(s,'/valid',{unknown:true})),'admission_rejection');assert.deepEqual(body.diagnostic,{stage:'admission',severity:'error',reason:'unknown_field',field:'$unknown'});}));
test('actual Host zero budget yields no-body control, not ready',()=>exercise('/valid',async(c,s)=>{assert.equal(received(await c.read(s,binding(s,'/valid',{budget_bytes:0})),'no_body_control'),null);}));
test('actual Host delivery failure stays transport_failure',()=>exercise('/failure',async(c,s)=>{assert.equal(received(await c.read(s,binding(s,'/failure')),'transport_failure'),null);}));
test('budget insufficient and old tuple never disclose component content',()=>exercise('/valid',async(c,s)=>{for(const req of [{budget_bytes:1000},{tuple:{...s.tuple,read:'kdna.read/0.1.0'}}]){const body=received(await c.read(s,binding(s,'/valid',req)));assert.equal(body.status,'rejected');assert.equal(body.content,null);}}));
test('retained actual HTTP read and typed expand retain remote proof limits, repeat and revocation',()=>exercise('/retained',async(c,s)=>{const first=received(await c.read(s,binding(s,'/retained')));assert.equal(first.status,'ready');assert.ok(first.content.expansion_handles.length);const handle=first.content.expansion_handles[0];for(let i=0;i<2;i++){const body=received(await c.read(s,binding(s,'/retained',{mode:'expand',handle},{expected_snapshot_id:first.snapshot_id})));assert.equal(body.status,'ready');assert.deepEqual(body.content.closure.map(x=>x.id).sort(),[...handle.scope].sort());assert.equal(body.snapshot_id,first.snapshot_id);}fixture.state.revoked=true;const result=await c.read(s,binding(s,'/retained',{mode:'expand',handle},{expected_snapshot_id:first.snapshot_id}));assert.notEqual(result.view?.response.body?.status,'ready');if(result.status==='received')assert.equal(result.view.response.body?.content??null,null);},{},withOptionalSupport()));
for(const [route,code] of [['/tamper-digest','READ_TRANSPORT_BINDING_MISMATCH'],['/tamper-schema','READ_TRANSPORT_SCHEMA_INVALID'],['/bare-200','READ_TRANSPORT_HTTP_MISMATCH'],['/malformed-json','READ_TRANSPORT_JSON_INVALID']])test('actual HTTP malformed/tampered response rejects: '+route,()=>exercise(route,async(c,s)=>failed(await c.read(s,binding(s,route)),code)));
test('association replay and stale context are rejected by public receiver',()=>exercise('/valid',async(c,s)=>{const ctx=binding(s);received(await c.read(s,ctx));failed(await c.read(s,ctx),'READ_TRANSPORT_ASSOCIATION_REPLAYED');failed(await c.read(s,binding(s,'/valid',{}, {issued_at_ms:Date.now()-2000,expires_at_ms:Date.now()-1})),'READ_TRANSPORT_ASSOCIATION_STALE');}));
test('file and endpoint context mismatch rejects before actual Fetch',()=>exercise('/valid',async(c,s)=>{failed(await c.read(s,binding(s,'/valid',{}, {endpoint_id:'other'})),'CLIENT_CONTEXT_MISMATCH');failed(await c.read(s,binding(s,'/valid',{}, {expected_digests:{A:'sha256:'+'0'.repeat(64),C:s.digests.C.observed,E:s.digests.E.observed}})),'CLIENT_SELECTION_MISMATCH');failed(await c.read({...s},binding(s)),'CLIENT_SELECTION_INVALID');}));
test('pre-abort rejects without starting Fetch',()=>exercise('/valid',async(c,s)=>failed(await c.read(s,binding(s),{signal:AbortSignal.abort()}),'CLIENT_CANCELLED'),{fetch:()=>{throw Error('must not call');}}));
test('actual Fetch abort produces no late view',()=>exercise('/delay',async(c,s)=>{const ac=new AbortController();const pending=c.read(s,binding(s,'/delay'),{signal:ac.signal});setTimeout(()=>ac.abort(),20);failed(await pending,'CLIENT_CANCELLED');}));
test('dispose and selection release cancel actual in-flight uploads',async()=>{for(const release of [false,true])await exercise('/delay',async(c,s)=>{const pending=c.read(s,binding(s,'/delay'));setTimeout(()=>release?releaseKDNASelection(s):c.dispose(),20);failed(await pending,release?'CLIENT_SELECTION_RELEASED':'CLIENT_DISPOSED');});});
test('overall timeout and busy slots remain bounded on actual HTTP',()=>exercise('/delay',async(c,s)=>{const p=c.read(s,binding(s,'/delay'));failed(await c.read(s,binding(s,'/delay')),'CLIENT_BUSY');failed(await p,'CLIENT_TIMEOUT');},{timeoutMs:30,maxConcurrentRequests:1}));
test('custom ignored abort retains slot until settlement and cannot publish late view',()=>exercise('/valid',async(c,s)=>{const p=c.read(s,binding(s));failed(await p,'CLIENT_TIMEOUT');failed(await c.read(s,binding(s)),'CLIENT_BUSY');await new Promise(r=>setTimeout(r,150));},{timeoutMs:15,maxConcurrentRequests:1,fetch:async(url,init)=>{const response=await fetch(url,{...init,signal:undefined});await new Promise(r=>setTimeout(r,100));return response;}}));
test('byte ownership protects selection against caller mutation',async()=>{const b=Uint8Array.from(rich);await exercise('/valid',async(c,s)=>{b.fill(0);assert.equal(received(await c.read(s,binding(s))).status,'ready');},{},b);});
test('network exceptions are sanitized and long request input rejected',()=>exercise('/valid',async(c,s)=>{const r=await c.read(s,binding(s));failed(r,'CLIENT_NETWORK_ERROR');assert.equal(JSON.stringify(r).includes('PRIVATE_SENTINEL'),false);failed(await c.read(s,binding(s,'/valid',{}, {outbound_request_json:' '.repeat(65537)})),'CLIENT_REQUEST_INVALID');},{fetch:async()=>{throw Error('PRIVATE_SENTINEL');}}));
