import {test} from 'node:test';
import assert from 'node:assert/strict';
import {selectKDNA,createKDNAWebClient,releaseKDNASelection} from '@aikdna/kdna-web-client';
import {bytesFor} from './fixtures.mjs';
let serial=0;
async function setup(options){const r=await selectKDNA(bytesFor('independent-mechanisms.kdna'));assert.equal(r.status,'selected');const s=r.selection,c=createKDNAWebClient({endpointUrl:'http://127.0.0.1:1/read',endpointId:'strict-endpoint',sessionId:'strict-session',...options});return {s,c,ctx(){const id='strict:'+ ++serial,req={request_id:id,tuple:s.tuple,budget_bytes:1000000,mode:'catalog',selection:null,handle:null};return {association_id:id,endpoint_id:'strict-endpoint',session_id:'strict-session',endpoint_url:'http://127.0.0.1:1/read',issued_at_ms:Date.now(),expires_at_ms:Date.now()+60000,outbound_request_json:JSON.stringify(req),correlation:{state:'validated',request_id:id},expected_tuple:s.tuple,expected_asset:s.asset,expected_digests:Object.fromEntries(['A','C','E'].map(k=>[k,s.digests[k].observed])),expected_snapshot_id:null,max_response_bytes:1000000,max_read_ms:5000,admission_response_limit_bytes:4096};},close(){c.dispose();releaseKDNASelection(s);}};}
test('strict injected pending Fetch: pre-abort does not call Fetch',async()=>{let calls=0;const f=await setup({fetch:()=>{calls++;return Promise.reject(Error());}});try{assert.equal((await f.c.read(f.s,f.ctx(),{signal:AbortSignal.abort()})).code,'CLIENT_CANCELLED');assert.equal(calls,0);}finally{f.close();}});
for(const kind of ['abort','dispose','release'])test('strict injected pending Fetch: '+kind+' prevents publication',async()=>{let settle,started;const ready=new Promise(r=>started=r);const f=await setup({fetch:()=>{started();return new Promise(r=>settle=r);}});const ac=new AbortController();try{const p=f.c.read(f.s,f.ctx(),{signal:ac.signal});await ready;if(kind==='abort')ac.abort();else if(kind==='dispose')f.c.dispose();else releaseKDNASelection(f.s);const r=await p;assert.equal(r.status,'failed');assert.equal(r.view,null);assert.equal(r.code,{abort:'CLIENT_CANCELLED',dispose:'CLIENT_DISPOSED',release:'CLIENT_SELECTION_RELEASED'}[kind]);settle(new Response(null));await new Promise(r=>setImmediate(r));assert.equal(r.view,null);}finally{f.close();}});
test('strict ignored-abort provider retains its bounded slot until settlement',async()=>{let settle;const f=await setup({timeoutMs:15,maxConcurrentRequests:1,fetch:()=>new Promise(r=>settle=r)});try{assert.equal((await f.c.read(f.s,f.ctx())).code,'CLIENT_TIMEOUT');assert.equal((await f.c.read(f.s,f.ctx())).code,'CLIENT_BUSY');settle(new Response(null));await new Promise(r=>setImmediate(r));}finally{f.close();}});
